version: '1.0.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
nuget:
  disable_publish_on_pr: true
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build . -v quiet
skip_commits:
  files:
    - '**/*.md'
