version: '3'
services:

  postgres:
    # For more details on configuring the Postgres Docker image, see:
    #   https://hub.docker.com/_/postgres/
    image: docker.io/postgres:12.4-alpine

    # Expose the default Postgres port on localhost
    ports:
      - '5432:5432'
    container_name: postgres

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'

  mysql:
    # For more details on configuring the Mysql Docker image, see:
    #   https://hub.docker.com/_/mysql
    image: docker.io/mysql/mysql-server:5.7

    # Expose the default Mysql port on localhost
    ports:
    - "3306:3306"
    container_name: mysql

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'test'

  sqlserver:
    image: docker.io/mcr.microsoft.com/mssql/server:2022-latest

    # Expose the default Sql Server port on localhost
    ports:
    - "1434:1433"
    container_name: sqlserver

    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssword123'
      MSSQL_PID: 'Enterprise'
